name: CI process for Symfony StarterKit

on:
  push:
  pull_request:

jobs:
  symfony:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Set up PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: '8.2'
          extensions: mbstring, xml, ctype, iconv, intl, pdo, dom, filter, gd, iconv, json, mbstring
          tools: php-cs-fixer
      - name: Install Composer dependencies
        run: composer install --no-progress --prefer-dist --optimize-autoloader
      - name: Run PHPStan
        run: vendor/bin/phpstan analyse
      - name: Run PHPCsFixer
        run: php-cs-fixer fix src tests --config=.php-cs-fixer.php --dry-run --diff --allow-risky=yes
      - name: Install test DB
        run: php bin/console doctrine:database:create --env=test
      - name: Run migrations
        run: php bin/console doctrine:migrations:migrate --env=test --no-interaction
      - name: Build assets
        run: php bin/console tailwind:build
      - name: Run tests
        run: php bin/phpunit
